bugfix: Don't assign to LINES and COLS
abishekvashok/cmatrix pull request #46
Opened 2018-06-13 16:12 UTC by acrisci

On some systems, these are macros that expand to function getters which cannot be assigned to.

fixes #40

2018-06-13 16:15 UTC, acrisci commented
On Cygwin, the LINES and COLS are defined [like this](https://github.com/mirror/ncurses/blob/e2e9c09c48b19b24979cafb2d4864f538b5ddd1c/include/ncurses_dll.h.in#L49-L54).

``` 
/*
 * For reentrant code, we map the various global variables into SCREEN by
 * using functions to access them.
*/
```

I hope there is no interaction between this and the `var_init()` function which may depend on these things being set. If there's more work to do for some edge cases I'm not aware of, let me know and I'll work on it. However, resizing seems to work for me with cygwin with this applied.

2018-06-14 17:17 UTC, abishekvashok requested changes
There are more places where they are used. Please change them as well as their definitions.

2018-06-14 17:32 UTC, acrisci commented
Are you saying you don't want to use the LINES or COLS global variables at all? And what definitions are you talking about?

2018-06-15 05:36 UTC, abishekvashok commented
Let me get more interactive:
> I hope there is no interaction between this and the var_init() function which may depend on these things being set.

Yes there is :)

2018-09-29 12:08 UTC, abishekvashok commented
@acrisci any updates?

2019-03-28 04:37 UTC, abishekvashok commented
Closing as obsolete

2019-03-28 04:37 UTC, closed without merging