Add:Rainbow mode,Fix:Window Resize Problem
abishekvashok/cmatrix pull request #8
Opened 2017-07-14 16:40 UTC by onurtore

Window resize problem fixed but its a hack.

2017-07-14 16:55 UTC, JonnyTech commented on cmatrix.c
> +                        int randomColor = rand() % 5;
Should this be 6? IIRC 5 will only generate 0 to 4.

2017-07-14 17:12 UTC, onurtore commented on cmatrix.c
> +                        int randomColor = rand() % 5;
yep you are right

2017-07-15 04:50 UTC, abishekvashok requested changes
The code looks good and it works. But it would be best if you could intend it properly.

2017-07-15 04:50 UTC, abishekvashok commented on cmatrix.c
> +
Please avoid using 3 empty lines and use only 1

2017-07-15 04:50 UTC, abishekvashok commented on cmatrix.c
> +
There's a tab

2017-07-15 04:50 UTC, abishekvashok commented on cmatrix.c
> +                    	switch(randomColor){
Please properly intend the code

2017-07-15 05:40 UTC, abishekvashok commented
Please check Travis @onurtore

2017-07-15 08:54 UTC, abishekvashok requested changes

2017-07-15 08:54 UTC, abishekvashok commented on cmatrix.spec
> +%define name    cmatrix
This file is dynamically generated from .spec.in file using auto tools for distribution as an rpm file. Please don't include it.

2017-07-15 09:06 UTC, abishekvashok approved these changes
Thanks

2017-07-15 09:10 UTC, merged